version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "4000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge

